gencode_gtf: ftp://ftp.ensembl.org/pub/release-98/gtf/mus_musculus/Mus_musculus.GRCm38.98.gtf.gz  # needs to be the same that was used for the RNA-seq pipeline
gencode_gtf_vM3: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M3/gencode.vM3.annotation.gtf.gz  # This was used for TargetScan v7.2

cluster_mutants:
  miR-290-295:
    member: 'mmu-miR-295-3p'
    file: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_miR290/DEseq_basic_DEresults{shrunk}.tsv'
  # miR-337-136:
  #   member: 'mmu-miR-127-3p'
  #   file: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_miR337/DEseq_basic_DEresults{shrunk}.tsv'
  # miR-182-183:
  #   member: 'mmu-miR-182-3p'
  #   file: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_miR182/DEseq_basic_DEresults{shrunk}.tsv'


siPOOL_targets:
  Tfap4: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_si_tfap4/DEseq_basic_DEresults{shrunk}.tsv'

full_effect_mutants:
  - Dgcr8
  - Drosha
  - Dicer
  - Ago12

other_mutants:
  - Ago1
  - Ago2

other_samples:
  - WT_2i

sample_colors:
  WT: '#8b4513'
  Ago12: '#Ff8c00'
  Dicer: '#912cee'
  Drosha: '#43cd80'
  Dgcr8: '#87ceff'
  old_miR290WT: '#8b4513'
  old_miR290: '#Ee3a8c'
  miR-290-295: '#Ee3a8c'
  miR290: '#Ee3a8c'  # workaround
  si_neg: '#8b4513'
  si_tfap4: '#Eee9bf'

add_tfs: [Elob]
remove_tfs: []
mrna_diffexp_path: cclab:/home/schamori/snakepipelines/rna-seq/DESeq2_{sample}/DEseq_basic_DEresults_LFCshrunk.tsv  # TODO required by mir290_ml/dataset generation (because of p-value...)
# bam_path: cclab:/home/schamori/snakepipelines/rna-seq/STAR/{sample}.bam  # not required
expression_path: cclab:/home/schamori/snakepipelines/rna-seq/featureCounts/counts.tsv
quant_seq_expression_path: cclab:/home/schamori/snakepipelines/quant-seq/featureCounts/counts.tsv

combined_padj_threshold: 0.3
padj_threshold: 0.1
log2fc_threshold: 0.5
# minimal expression
basemean_threshold: 10
mirna_threshold: 10
# TPM threshold
mrna_threshold: 1
ts_threshold: -0.00

# for figure 2
target_params:
  Zic2:
    chr: '14'
    start: 122478858
    end: 122480347
    strand: '+'
  # Wiz:
  #   chr: '17'
  #   start: 32353813
  #   end: 32355267
  #   strand: '-'
  Tfap4:
    chr: '16'
    start: 4544545
    end: 4545861
    strand: '-'
  Apoe:   # positive example (HEAP-peak in CDS)
    chr: '7'
    start: 19696000
    end: 19697900
    strand: '-'
  # Ubxn1:   # positive example
  #   chr: 19
  #   start: 8873400
  #   end: 8876130
  #   strand: '+'
  # Mt1:   # positive example
  #   chr: 8
  #   start: 94179800
  #   end: 94180350
  # Prr13:   # positive example
  #   chr: 15
  #   start: 102462100
  #   end: 102462940
  Axin2:   # negative example
    chr: '11'
    start: 108949100
    end: 108950900
    strand: '+'
  # Thsd1:   # negative example
  #   chr: '8'
  #   start: 22256000
  #   end: 22262500
  #   strand: '+'
  # Zfp85:  # negative example
  #   chr: '13'
  #   start: 67747000
  #   end: 67750000
  #   strand: '-'
  # Pipox:  # delete
  #   chr: '11'
  #   start: 77880455
  #   end: 77881951
  #   strand: '-'
  # Aars:
  #   chr: '8'
  #   start: 111054117
  #   end: 111057874
  #   strand: '+'
  Ctcf:
    chr: '8'
    start: 105681183
    end: 105683084
    strand: '+'
  Gdf15:  # too much peak in 3'UTR
    chr: '8'
    start: 70629154
    end: 70632615
    strand: '-'
  # Mvp:
  #   chr: '7'
  #   start: 126985580
  #   end: 126990567 
  #   strand: '-'
  Rps26: # chosen
    chr: '10'
    start: 128624190
    end: 128625000
    strand: '-'

# other negative candidates:
# - Lag3
# - Utp3 # maybe. why not TS scores?
# - Zfp951
