gencode_gtf: ftp://ftp.ensembl.org/pub/release-98/gtf/mus_musculus/Mus_musculus.GRCm38.98.gtf.gz  # needs to be the same that was used for the RNA-seq pipeline
gencode_gtf_vM3: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M3/gencode.vM3.annotation.gtf.gz  # This was used for TargetScan v7.2

cluster_mutants:
  miR-290-295:
    member: 'mmu-miR-295-3p'
    file: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_miR290/DEseq_basic_DEresults{shrunk}.tsv'
  # miR-337-136:
  #   member: 'mmu-miR-127-3p'
  #   file: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_miR337/DEseq_basic_DEresults{shrunk}.tsv'
  # miR-182-183:
  #   member: 'mmu-miR-182-3p'
  #   file: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_miR182/DEseq_basic_DEresults{shrunk}.tsv'


siPOOL_targets:
  Tfap4: 'cclab:/home/schamori/snakepipelines/quant-seq/DESeq2_si_tfap4/DEseq_basic_DEresults{shrunk}.tsv'
  
full_effect_mutants:
  - Drosha
  - Dicer
  - Ago12

other_mutants:
  - Ago1
  - Ago2

other_samples:
  - WT_2i

sample_colors:
  WT: '#8b4513'
  Ago12: '#Ff8c00'
  Dicer: '#912cee'
  Drosha: '#43cd80'
  old_miR290WT: '#8b4513'
  old_miR290: '#Ee3a8c'
  miR-290-295: '#Ee3a8c'
  miR290: '#Ee3a8c'  # workaround
  si_neg: '#8b4513'
  si_tfap4: '#Eee9bf'

add_tfs: [Elob]
remove_tfs: []
mrna_diffexp_path: cclab:/home/schamori/snakepipelines/rna-seq/DESeq2_{sample}/DEseq_basic_DEresults_LFCshrunk.tsv  # TODO required by mir290_ml/dataset generation (because of p-value...)
# bam_path: cclab:/home/schamori/snakepipelines/rna-seq/STAR/{sample}.bam  # not required
expression_path: cclab:/home/schamori/snakepipelines/rna-seq/featureCounts/counts.tsv
quant_seq_expression_path: cclab:/home/schamori/snakepipelines/quant-seq/featureCounts/counts.tsv

min_num_up_genes: 2
combined_padj_threshold: 0.2
padj_threshold: 0.1
log2fc_threshold: 0.0
# minimal expression
basemean_threshold: 10
mirna_threshold: 10
# TPM threshold
mrna_threshold: 1
ts_threshold: -0.00

# for figure 2
target_params:
  Tfap4:
    chr: '16'
    start: 4544545
    end: 4545861
    strand: '-'
  Apoe:   # positive example (HEAP-peak in CDS)
    chr: '7'
    start: 19696000
    end: 19697900
    strand: '-'
  Ubxn1:   # positive example
    chr: '19'
    start: 8873400
    end: 8876130
    strand: '+'
  Mt1:   # positive example
    chr: '8'
    start: 94179800
    end: 94180350
    strand: '+'
  Prr13:   # positive example
    chr: '15'
    start: 102462100
    end: 102462840
    strand: '+'
  Axin2:   # negative example
    chr: '11'
    start: 108949100
    end: 108950900
    strand: '+'
  Ctcf:
    chr: '8'
    start: 105681183
    end: 105683084
    strand: '+'
  Rps26:
    chr: '10'
    start: 128624190
    end: 128625000
    strand: '-'
  Cdkn1a:
    chr: '17'
    start: 29090976
    end: 29100727
    strand: '+'

mre_count_bins: [1, 2, 5, 10, 20]
ts_mre_count_bins: [1, 2, 5, 25, 100]

# other negative candidates:
# - Lag3
# - Utp3 # maybe. why not TS scores?
# - Zfp951
